version: "3"
services:
  php:
    build: .
    ports: ["8080:80"]
  db:
    image: "docker.io/library/mariadb:10.6"
    command: >-
      --innodb-buffer-pool-size=1024M
      --query-cache-size=16M
      --max-allowed-packet=64M
      --query-cache-limit=5M
      --sql-mode=
    environment:
      - MARIADB_ROOT_PASSWORD=insecure
